#!/bin/bash

function tmuximum_help() {
  echo "tmuximum: Usage"
  echo "$ tmuximum [OPTION]"
  echo "OPTIONS : \"-h\" --> Display help message (this message)"
  echo "To quit tmuximum, press esc" 
}

function tmuximum_operation() {
  answer=$(tmuximum_operation_list | "${filter[@]}" --select-1 --prompt=tmuximum\ \>)
  case $answer in
    *new\ session* ) tmux new-session ;;
    *new\ window* ) tmux new-window ;;
    "kill sessions" ) tmuximum_kill_session ;;
    "kill windows" ) tmuximum_kill_window ;;
    *move* ) tmux select-window -t $(echo  "$answer" | awk '{print $4}' | sed "s/://g") ;;
    *attach* ) tmux attach -t $(echo "$answer" | awk '{print $4}' | sed 's/://') ;;
  esac
}

function tmuximum_operation_list() {
  if [ -z $TMUX ]; then
    tmux list-sessions 2>/dev/null | while read line; do
      [[ ! "$line" =~ "attached" ]] || line="${GREEN}$line${DEFAULT}"
      echo -e "${GREEN}attach${DEFAULT} ==> [ "$line" ]"
    done
    echo -e "${GREEN}create${DEFAULT} ==> [ ${BLUE}new session${DEFAULT} ]"
  else
    tmux list-windows | sed "/active/d" | while read line; do
      echo -e  "${CYAN}move${DEFAULT} ==> [ $(echo $line | awk '{print $1 " " $2 " " $3 " " $4 " " $5}') ]"
    done
    echo -e  "${CYAN}move${DEFAULT} ==> [ ${BLUE}new window${DEFAULT} ]"
    echo -e "${RED}kill${DEFAULT} windows"
  fi
  tmux has-session 2>/dev/null && echo -e "${RED}kill${DEFAULT} sessions"
}

function tmuximum_kill_session() {
  answer=$(tmuximum_kill_session_list | "${filter[@]}" --select-1 --prompt=tmuximum\ \>)
  case $answer in
    *kill*Server* ) tmux kill-server ; tmuximum_operation ;;
    *kill*windows* ) tmux kill-session -t $(echo "$answer" | awk '{print $4}' | sed "s/://g")
      if $(tmux has-session 2>/dev/null); then
        tmuximum_kill_session
      fi
    ;;
  "back" ) tmuximum_operation
  esac
}

function tmuximum_kill_session_list() {
  list_sessions=$(tmux list-sessions 2>/dev/null);
  echo "$list_sessions" | while read line; do
    [[ "$line" =~ "attached" ]] && line="${GREEN}"$line"${DEFAULT}"
    echo -e  "${RED}kill${DEFAULT} ==> [ "$line" ]"
  done
  [ $(echo "$list_sessions" | grep -c '')  = 1 ] || echo "${RED}kill${DEFAULT} ==> [ ${RED}Server${DEFAULT} ]"
  echo -e "${BLUE}back${DEFAULT}"
}

function tmuximum_kill_window() {
  answer=$(tmuximum_kill_window_list | "${filer[@]}" --select-1 --prompt=tmuximum\ \>)
  if [[ "$answer" =~ "kill" ]]; then
    tmux kill-window -t $(echo "$answer" | awk '{print $4}' | sed "s/://g")
    tmuximum_kill_window
  elif [[ $answer = "back" ]]; then
    tmuximum_operation
  fi
}

function tmuximum_kill_window_list() {
  tmux list-windows | while read line ; do
    line="$(echo $line | awk '{print $1 " " $2 " " $3 " " $4 " " $5 " " $9}')"
    [[ $line =~ "active" ]] && line="${GREEN}$line${DEFAULT}"
    echo -e " ${RED}kill${DEFAULT} ==> [ $line ]"
  done
  echo -e "${BLUE}back${DEFAULT}"
}

set_color() {
  readonly BLACK="\033[30m"
  readonly RED="\033[31m"
  readonly GREEN="\033[32m"
  readonly YELLOW="\033[33m"
  readonly BLUE="\033[34m"
  readonly MAGENTA="\033[35m"
  readonly CYAN="\033[36m"
  readonly WHITE="\033[37m"
  readonly BOLD="\033[1m"
  readonly DEFAULT="\033[m"
}

function main() {
  set_color
# set_filter
  filter=(fzf-tmux --ansi)
  if [[ $# = 0 ]]; then
    tmuximum_operation
  elif [[ $# = 1 ]]; then
    case $1 in
      "-h" ) tmuximum_help ;;
      * ) echo "tmuximum: illegal option $1" && exit 1
    esac
  else
    echo "tmuximum: option must be one" && exit 1
  fi
}

main $@
