#!/bin/zsh

if [[ $SHELL =~ "zsh" ]] ; then
  autoload -Uz colors
  colors
fi

tmuximum_help() {
  echo "tmuximum: Usage"
  echo "          OPTION or COMMAND is not required (Except for help)"
  echo "          When you want to quit tmuximum, press esc" 
  echo "          To read this help, enter \"tmuximum --help\" or \" tmuximum help\""
}

tmuximum_operation() {
  answer=$(tmuximum_operation_list | $interface --ansi --select-1 --prompt="tmuximum >")
  case $answer in
    *new\ session* ) tmux new-session ;;
    *new\ window* ) tmux new-window ;;
    "kill sessions" ) tmuximum_kill_session ;;
    "kill windows" ) tmuximum_kill_window ;;
    "kill panes" ) tmuximum_kill_pane ;;
    *switch* ) tmux select-window -t $(echo "$answer" | awk '{print $4}' | sed "s/://g") ;;
    *attach* ) tmux attach -t $(echo "$answer" | awk '{print $4}' | sed 's/://') ;;
  esac
}

tmuximum_operation_list() {
  if [ -z $TMUX ]; then
    tmux list-sessions 2>/dev/null | while read line; do
      [[ ! "$line" =~ "attached" ]] || line="${fg[green]}$line${reset_color}"
      echo "${fg[green]}attach${reset_color} ==> [ "$line" ]"
    done
    echo "${fg[green]}create${reset_color} ==> [ ${fg[blue]}new session${reset_color} ]"
  else
    tmux list-windows | sed "/active/d" | while read line; do
      echo  "${fg[cyan]}switch${reset_color} ==> [ $(echo $line | awk '{print $1 " " $2 " " $3 " " $4 " " $5}') ]"
    done
    tmux list-panes | sed "/active/d" | while read line; do
      echo  "${fg[cyan]}switch${reset_color} ==> [ $(echo $line | awk '{print $1 " " $2 " " $3 " " $4 " " $5}') ]"
    done
    echo  "${fg[cyan]}switch${reset_color} ==> [ ${fg[blue]}new window${reset_color} ]"
    echo "${fg[red]}kill${reset_color} windows"
  fi
  tmux has-session 2>/dev/null && echo "${fg[red]}kill${reset_color} sessions"
}

tmuximum_kill_session() {
  answer=$(tmuximum_kill_session_list | $interface  --ansi --prompt="tmuximum >")
  case $answer in
    *kill*Server* ) tmux kill-server ; tmuximum_operation ;;
    *kill*windows* ) tmux kill-session -t $(echo "$answer" | awk '{print $4}' | sed "s/://g")
      if $(tmux has-session 2>/dev/null); then
        tmuximum_kill_session
      fi
    ;;
  "back" ) tmuximum_operation
  esac
}

tmuximum_kill_session_list() {
  list_sessions=$(tmux list-sessions 2>/dev/null);
  echo "$list_sessions" | while read line; do
    [[ "$line" =~ "attached" ]] && line="${fg[green]}"$line"${reset_color}"
    echo  "${fg[red]}kill${reset_color} ==> [ "$line" ]"
  done
  [ $(echo "$list_sessions" | grep -c '')  = 1 ] || echo "${fg[red]}kill${reset_color} ==> [ ${fg[red]}Server${reset_color} ]"
  echo "${fg[blue]}back${reset_color}"
}

tmuximum_kill_window() {
  answer=$(tmuximum_kill_window_list | $interface --ansi --prompt="tmuximum >")
  if [[ "$answer" =~ "kill" ]]; then
    tmux kill-window -t $(echo "$answer" | awk '{print $4}' | sed "s/://g")
    tmuximum_kill_window
  elif [[ $answer = "back" ]]; then
    tmuximum_operation
  fi
}

tmuximum_kill_window_list() {
  tmuximum list-windows | while read line ; do
    line="$(echo $line | awk '{print $1 " " $2 " " $3 " " $4 " " $5 " " $9}')"
    [[ $line =~ "active" ]] && line="${fg[green]}$line${reset_color}"
    echo " ${fg[red]}kill${reset_color} ==> [ $line ]"
  done
  echo "${fg[blue]}back${reset_color}"
}

tmuximum_kill_pane() {
  answer=$(tmuximum_kill_pane_list | $interface --ansi --prompt="tmuximum >")
  if [[ "$answer" =~ "kill" ]]; then
    tmux kill-pane -t $(echo "$answer" | awk '{print $4}' | sed "s/://g")
    tmuximum_pane
  elif [[ $answer = "back" ]]; then
    tmuximum_operation
  fi
}

tmuximum_kill_pane_list() {
  tmuximum list-pane | while read line ; do
    line="$(echo $line | awk '{print $1 " " $2 " " $3 " " $4 " " $5 " " $9}')"
    [[ $line =~ "active" ]] && line="${fg[green]}$line${reset_color}"
    echo " ${fg[red]}kill${reset_color} ==> [ $line ]"
  done
  echo "${fg[blue]}back${reset_color}"
}

if which fzf-tmux >/dev/null 2>&1 ; then
  $interface="fzf-tmux"
elif which fzf >/dev/null 2>&1 ; then
  $interface="fzf"
else
  echo "tmuximum: fzf or fzf-tmux is required."
  exit 1
fi

if [[ $# = 0 ]] ; then
  tmuximum_operation
else
  tmuximum_help
  if [[ ! $# = 1 ]] || [[ ! $1 =~ help ]] ; then
    exit 1
  fi
fi

